#Google Chrome Path in Windows 10
  """ 
  #Windows 10:
  %ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe
  %ProgramFiles%\Google\Chrome\Application\chrome.exe
  %LocalAppData%\Google\Chrome\Application\chrome.exe
  #Windows 7:
  C:\Program Files (x86)\Google\Application\chrome.exe
  #Vista:
  C:\Users\UserName\AppDataLocal\Google\Chrome
  #XP:
  C:\Documents and Settings\UserName\Local Settings\Application Data\Google\Chrome

  """


